### ISSUE TITLE
How to compute alpha search?

### ISSUE THREAD

**Issue by namespace-Pt** [jzhoubu/Vsearch#6]
I saw alpha search is an inner product between the BOW representation of query and the latent representation of doc. How is this done? The dimensions are not the same.

**Comment by jzhoubu** [comment]
Hi @namespace-Pt 

We use lexical representation for retrieval where the dimensionality match the BERT vocabualry size (e.g., 30522). Our BoW use BERT vocab as its dictionary, so their dimension match.

**Comment by namespace-Pt** [comment]
So alpha search is similar to doc-side SPLADE and the beta search is similar to query-side SPLADE. Am I right?

**Comment by svdr-nips2024** [comment]
Yes, you’re right in comparing alpha search to doc-side SPLADE and beta search to query-side SPLADE. There are some differences, but broadly, that’s correct.

**Comment by namespace-Pt** [comment]
Thanks a lot.

**Comment by jzhoubu** [comment]
You're welcome. Feel free to ask if you have more questions in the future.
